name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      # 1. Kod deposunu al
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Tüm geçmiş analiz için gerekli

      # 2. JDK 17 (bazı Sonar analizleri için gerekli olabilir)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      # 3. Node.js ortamı kur
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 4. SonarCloud cache
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 5. Bağımlılıkları yükle
      - name: Install dependencies
        run: npm ci

      # 6. Testleri çalıştır ve coverage üret
      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false

      # 7. SonarCloud Analizi
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # PR yorumları için
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Senin SonarCloud secret’in
